### PR TITLE
build: bump to lodash4, use rollup

### PR DESCRIPTION
**Pull request by frenautvh**
- bump from lodash 3 to 4 (fix github securities issues)
- kill Grunt, use rollup to build the library

⚠️ i need to do some further testing to ensure there are no regression ⚠️ 

Note : in order to not have to rewrite the full library with es6 imports, i'm using "rollup-plugin-glob-import" to import all the sources. I think it's a nice workaround because we can already start using imports for future updates and we can still refactor some part of the source code later

Also the eslint config is still the "old" one, i don't plan to update it now, it's not in the scope of this pull request

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build#1045.0 ✘  
* 
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#1047.0 ✘  
* 
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#1048.0 ✘  
* 
  * build ✘  
  * test ✘

**Comment by antleblanc** [comment]
Wouldn't be considered as an Breaking Changes?

The `dist` folder structure has changed and we lose the minified version too.

**Comment by ovh-cds** [comment]
CDS Report build#1069.0 ✘  
* 
  * build ✘  
  * test ✘

**Comment by ovh-cds** [comment]
CDS Report build#1077.0 ✘  
* 
  * build ✘  
  * test ✘

**Pull request merged**
